"""Cooling UI is Fan Control-like with confirmed PWM take-over."""
from __future__ import annotations

import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


class CoolingUiTests(unittest.TestCase):
    def test_helpers_and_locales(self) -> None:
        lib = (ROOT / "apps/desktop/src/lib/cooling.js").read_text(encoding="utf-8")
        self.assertIn("export function milliC", lib)
        self.assertIn("export function pwmPercent", lib)
        self.assertIn("export function fanDutyPct", lib)
        self.assertIn("export function groupName", lib)
        self.assertIn("export function curvePoints", lib)
        self.assertIn("export function curveDots", lib)
        self.assertIn("export function controlCards", lib)
        self.assertIn("export function emptyHeader", lib)
        self.assertIn("export function onBoard", lib)
        self.assertIn("export function inHiddenRow", lib)
        self.assertIn("gpuFans", lib)
        board = (ROOT / "apps/desktop/src/lib/coolingBoard.js").read_text(encoding="utf-8")
        self.assertIn("FAN4", board)
        self.assertIn("FAN5_PUMP", board)
        self.assertIn("FAN7_PUMP", board)
        self.assertIn("SYS_FAN1", board)
        self.assertIn("CPU_FAN", board)
        self.assertIn("aioMemberIds", board)
        self.assertNotIn("set_pwm", board)
        rust = (ROOT / "crates/chromaflow-core/src/nvidia_fans.rs").read_text(encoding="utf-8")
        self.assertIn("GPUCurrentFanSpeedRPM", rust)
        self.assertIn("XAUTHORITY", rust)
        self.assertIn('arg("-c")', rust)
        self.assertNotIn("set_pwm", rust)
        self.assertIn("fanForPwm", lib)
        self.assertIn("fan${n}_input", lib)
        gaps = (ROOT / "crates/chromaflow-core/src/gaps.rs").read_text(encoding="utf-8")
        self.assertIn("ite_primary_missing", gaps)
        spec = (ROOT / "docs/features/cooling-fans.md").read_text(encoding="utf-8")
        self.assertIn("NVIDIA", spec)
        self.assertIn("export function tunedCurve", lib)
        self.assertIn("export function tempSources", lib)
        self.assertNotIn("set_pwm", lib)
        curves = (ROOT / "apps/desktop/src/lib/coolingCurves.js").read_text(encoding="utf-8")
        self.assertIn("[25, 20]", curves)
        self.assertIn("[90, 100]", curves)
        self.assertIn("full", curves)
        self.assertIn("[25, 100]", curves)
        mix = (ROOT / "apps/desktop/src/lib/coolingMix.js").read_text(encoding="utf-8")
        self.assertIn("gauge:cpu", mix)
        self.assertIn("gauge:gpu", mix)
        self.assertIn("usagePct", mix)
        self.assertIn('"max"', mix)
        gauges = (ROOT / "apps/desktop/src/lib/gauges.js").read_text(encoding="utf-8")
        self.assertIn("cpu_load: g && g.cpu_load", gauges)
        pwm = (ROOT / "apps/desktop/src/lib/pwm.js").read_text(encoding="utf-8")
        self.assertIn("export function canControl", pwm)
        self.assertIn("export function confirmTakeover", pwm)
        self.assertIn("export function cardForChannel", pwm)
        self.assertIn("curve_id", pwm)
        self.assertIn("temp_id", pwm)
        locales = (ROOT / "apps/desktop/src/locales/en.json").read_text(encoding="utf-8")
        self.assertIn("cooling.hysteresis", locales)
        self.assertIn("cooling.notApplied", locales)
        self.assertIn("cooling.takeoverAsk", locales)
        self.assertIn("chromaflowd", locales)
        self.assertIn("cooling.zeroAsk", locales)
        self.assertIn("cooling.fans", locales)
        self.assertIn("cooling.calibrate", locales)
        self.assertIn("cooling.aioUnit", locales)
        self.assertIn("cooling.unplugged", locales)
        self.assertIn("cooling.usageGraph", locales)
        self.assertIn("cooling.tempGraph", locales)
        self.assertIn("cooling.addMix", locales)
        self.assertIn("cooling.addCurve", locales)
        self.assertIn("fc-tile", (ROOT / "apps/desktop/src/lib/TempsList.svelte").read_text(encoding="utf-8"))
        self.assertIn("fc-spark", (ROOT / "apps/desktop/src/lib/SparkGraph.svelte").read_text(encoding="utf-8"))
        self.assertIn("fc-plus", (ROOT / "apps/desktop/src/lib/TempsList.svelte").read_text(encoding="utf-8"))
        self.assertIn("fc-plus", (ROOT / "apps/desktop/src/lib/CurvesList.svelte").read_text(encoding="utf-8"))
        spark = (ROOT / "apps/desktop/src/lib/spark.js").read_text(encoding="utf-8")
        self.assertIn("(n - 25) / 65", spark)
        self.assertIn("cpu_load", spark)
        self.assertIn("gridXs", spark)
        self.assertIn("every = 15", spark)
        self.assertNotIn("set_pwm", spark)
        css = (ROOT / "apps/desktop/src/app.css").read_text(encoding="utf-8")
        self.assertIn("overflow: hidden", css)
        self.assertIn("html, body", css)
        self.assertIn("--fc-tile-h: 22rem", css)
        self.assertIn("height: var(--fc-tile-h)", css)
        self.assertIn("grid-auto-rows: var(--fc-tile-h)", css)
        self.assertIn("fc-fill", css)
        self.assertIn("flex: 1 1 0", css)
        self.assertNotIn("fc-empty", css)
        self.assertIn("fc-ctrl", (ROOT / "apps/desktop/src/lib/ControlList.svelte").read_text(encoding="utf-8"))
        self.assertNotIn("fc-empty", (ROOT / "apps/desktop/src/lib/ControlList.svelte").read_text(encoding="utf-8"))
        self.assertNotIn("fc-ctrl-foot", (ROOT / "apps/desktop/src/lib/ControlList.svelte").read_text(encoding="utf-8"))
        self.assertIn("fc-fill", (ROOT / "apps/desktop/src/lib/CurvesList.svelte").read_text(encoding="utf-8"))
        self.assertNotIn(":not(.fc-curve)", css)
        self.assertNotIn("min-height: 33rem", css)
        self.assertNotIn("content-visibility: auto", css)
        self.assertNotIn("select multiple", (ROOT / "apps/desktop/src/lib/TempsList.svelte").read_text(encoding="utf-8"))
        controls = (ROOT / "apps/desktop/src/lib/ControlList.svelte").read_text(encoding="utf-8")
        self.assertIn("cooling.aioUnit", controls)
        self.assertIn("curveLabel", controls)
        self.assertNotIn("cooling.tune", controls)
        self.assertNotIn("cooling.calibrate", controls)
        self.assertNotIn("{#if card.backend === \"nvidia\"", controls)
        self.assertIn("cooling.mix.max", locales)
        page = (ROOT / "apps/desktop/src/pages/Cooling.svelte").read_text(encoding="utf-8")
        self.assertIn("from \"../lib/cooling.js\"", page)
        self.assertIn("from \"../lib/pwm.js\"", page)
        self.assertIn("from \"../lib/coolingPersist.js\"", page)
        persist = (ROOT / "apps/desktop/src/lib/coolingPersist.js").read_text(encoding="utf-8")
        self.assertIn("export function stateFromFile", persist)
        self.assertIn("export function fileFromState", persist)
        self.assertIn("export function applyPreset", persist)
        self.assertIn("export function canApplyRecipe", persist)
        self.assertIn("ch.enabled", persist)
        self.assertIn("file.hidden", persist)
        self.assertNotIn("set_pwm", persist)
        self.assertIn("cooling.noTakeover", page)
        self.assertIn("FansList", page)
        self.assertIn("PumpsList", page)
        self.assertIn("TempsList", page)
        self.assertIn("CurvesList", page)
        self.assertIn("pwm_takeover", page)
        self.assertIn("pwm_release", page)
        self.assertIn("onCalibrateAll", page)
        self.assertIn("fc-cal-all", page)
        self.assertIn("fc-save", page)
        self.assertIn("onSave", page)
        self.assertIn("savedToast", page)
        self.assertIn("fc-toast", page)
        self.assertIn("cooling.save", locales)
        self.assertIn("cooling.saved", locales)
        self.assertIn("onBoard", page)
        self.assertIn("inHiddenRow", page)
        self.assertIn("tucked", page)
        self.assertIn("function reveal", page)
        self.assertIn("onApplyAll", page)
        self.assertIn("applyPreset", page)
        self.assertIn("hydrated", page)
        self.assertIn("canApplyRecipe", page)
        self.assertIn("export let live", page)
        self.assertIn("cooling.applyAll", locales)
        rust_curves = (ROOT / "crates/chromaflow-core/src/pwm_curves.rs").read_text(encoding="utf-8")
        self.assertIn("pub hidden", rust_curves)
        self.assertIn("pub shown", rust_curves)
        self.assertIn("pwm_calibrate", (ROOT / "apps/desktop/src/lib/coolingSweep.js").read_text(encoding="utf-8"))
        self.assertIn("pickList", page)
        self.assertIn("allCurves", page)
        self.assertNotIn("pwm_tick", page)
        self.assertNotIn("hardware_gauges", page)
        self.assertNotIn("pushSample", page)
        temps = (ROOT / "apps/desktop/src/lib/TempsList.svelte").read_text(encoding="utf-8")
        self.assertNotIn("hardware_gauges", temps)
        self.assertNotIn("pushSample", temps)
        self.assertNotIn("setInterval(tick, 1000)", temps)
        self.assertIn("export let hist", temps)
        self.assertIn("SparkGraph", temps)
        app = (ROOT / "apps/desktop/src/App.svelte").read_text(encoding="utf-8")
        self.assertIn("startGaugeTick", app)
        self.assertIn("{gauges} {hist}", app)
        gauges_tick = (ROOT / "apps/desktop/src/lib/gaugesTick.js").read_text(encoding="utf-8")
        self.assertIn("hardware_gauges", gauges_tick)
        self.assertIn("GAUGE_POLL_MS = 400", gauges_tick)
        self.assertIn("GAUGE_HIST = 150", gauges_tick)
        self.assertNotIn("cycleOn", gauges_tick)
        self.assertNotIn("set_pwm", gauges_tick)
        scheme = (ROOT / "crates/chromaflow-core/src/pwm_scheme.rs").read_text(encoding="utf-8")
        self.assertIn("balanced", scheme)
        self.assertIn("gauge:cpu", scheme)
        self.assertNotIn("set_pwm", scheme)
        cli = (ROOT / "crates/chromaflow-cli/src/cooling.rs").read_text(encoding="utf-8")
        self.assertIn("run_takeover", cli)
        self.assertIn("0 RPM, skip", cli)
        self.assertNotIn("set_pwm", cli)
        apply = (ROOT / "crates/chromaflow-core/src/pwm_apply.rs").read_text(encoding="utf-8")
        self.assertIn("hwmon chip", apply)
        self.assertIn("points_for", apply)
        self.assertNotIn("set_pwm", apply)
        self.assertIn("cooling --takeover", (ROOT / "crates/chromaflow-cli/src/main.rs").read_text(encoding="utf-8"))
        self.assertIn("locales/en.json", page)
        self.assertIn("role=\"alert\"", page)
        self.assertIn("fc-shell", page)
        self.assertIn("controlCards", page)
        fans = (ROOT / "apps/desktop/src/lib/FansList.svelte").read_text(encoding="utf-8")
        self.assertIn("fanDutyPct", (ROOT / "apps/desktop/src/lib/ControlList.svelte").read_text(encoding="utf-8"))
        self.assertNotIn("set_pwm", fans)
        recipe = (ROOT / "crates/chromaflow-core/src/pwm_recipe.rs").read_text(encoding="utf-8")
        self.assertIn("gauge:cpu", recipe)
        self.assertIn("mix:", recipe)
        self.assertIn("points_for", recipe)
        self.assertIn("\"full\"", recipe)
        self.assertIn("flat_full", recipe)
        self.assertIn("flat_full", apply)
        self.assertNotIn("set_pwm", recipe)
        mix = (ROOT / "apps/desktop/src/lib/coolingMix.js").read_text(encoding="utf-8")
        self.assertIn("export function pickList", mix)
        self.assertIn("allCurves", (ROOT / "apps/desktop/src/lib/coolingCurves.js").read_text(encoding="utf-8"))
        self.assertIn("ui.scrolling", (ROOT / "apps/desktop/src/App.svelte").read_text(encoding="utf-8"))
        self.assertIn("$pwmOn", (ROOT / "apps/desktop/src/App.svelte").read_text(encoding="utf-8"))
        self.assertIn("anyTaken", (ROOT / "apps/desktop/src/pages/Cooling.svelte").read_text(encoding="utf-8"))
        self.assertIn("export const pwmOn", (ROOT / "apps/desktop/src/lib/ui.js").read_text(encoding="utf-8"))
        self.assertIn("lightInv", (ROOT / "apps/desktop/src/App.svelte").read_text(encoding="utf-8"))
        self.assertIn("beforeunload", (ROOT / "apps/desktop/src/App.svelte").read_text(encoding="utf-8"))
        self.assertIn("controllers || []).length", (ROOT / "apps/desktop/src/App.svelte").read_text(encoding="utf-8"))
        self.assertIn('{#if tab === "Cooling"}', (ROOT / "apps/desktop/src/App.svelte").read_text(encoding="utf-8"))
        self.assertIn('live={source === "this machine"}', (ROOT / "apps/desktop/src/App.svelte").read_text(encoding="utf-8"))
        self.assertIn("collect_cooling", (ROOT / "crates/chromaflow-core/src/scan.rs").read_text(encoding="utf-8"))
        self.assertIn("inline-flex", css)
        self.assertIn("cooling.clone", locales)
        self.assertIn("cooling.quietHelp", locales)
        self.assertIn("cooling.full", locales)
        self.assertIn("cooling.fullHelp", locales)
        self.assertIn("cooling.calibrateProgress", locales)
        self.assertNotIn("cooling.tune", locales)
        curves_ui = (ROOT / "apps/desktop/src/lib/CurvesList.svelte").read_text(encoding="utf-8")
        self.assertIn("cloneCurve", curves_ui)
        self.assertIn("cooling.clone", curves_ui)
        self.assertIn("cooling.applyAll", curves_ui)
        self.assertIn('preset.id !== "full"', curves_ui)
        self.assertIn("fc-curve-actions", curves_ui)
        self.assertIn("fc-curve-head", curves_ui)
        self.assertIn("fc-curve-actions", css)
        self.assertIn("fc-curve-head", css)
        self.assertIn("fc-toast", css)
        self.assertIn("fc-toolbar-actions", css)
        graph = (ROOT / "apps/desktop/src/lib/CurveGraph.svelte").read_text(encoding="utf-8")
        self.assertIn("25°C", graph)
        self.assertIn("100%", graph)
        self.assertIn("xMidYMid meet", graph)
        self.assertNotIn("fc-pt", graph)
        self.assertIn("plotX", (ROOT / "apps/desktop/src/lib/coolingCurves.js").read_text(encoding="utf-8"))
        self.assertIn("cloneCurve", (ROOT / "apps/desktop/src/lib/coolingCurves.js").read_text(encoding="utf-8"))
        sweep = (ROOT / "apps/desktop/src/lib/coolingSweep.js").read_text(encoding="utf-8")
        self.assertIn("export function sweepQueue", sweep)
        self.assertIn("emptyHeader", sweep)
        self.assertIn("export async function sweepEach", sweep)
        self.assertNotIn("set_pwm", sweep)
        spec = (ROOT / "docs/features/cooling-ui.md").read_text(encoding="utf-8")
        self.assertIn("take-over", spec.lower() + spec)
        self.assertIn("Fans", spec)
        self.assertIn("wireframe", spec.lower() + spec)


if __name__ == "__main__":
    unittest.main()
