"""Tauri 2 host exists and CI installs WebKit instead of skipping both distros."""
from __future__ import annotations

import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


class TauriStubTests(unittest.TestCase):
    def test_desktop_crate_is_tauri(self) -> None:
        cargo = (ROOT / "apps/desktop/src-tauri/Cargo.toml").read_text(encoding="utf-8")
        self.assertIn("tauri-build", cargo)
        self.assertIn("workspace = true", cargo)
        self.assertIn("image-png", cargo)
        main = (ROOT / "apps/desktop/src-tauri/src/main.rs").read_text(encoding="utf-8")
        self.assertIn("refuse_if_root", main)
        self.assertIn("support_dry_run", main)
        self.assertIn("support_apply", main)
        self.assertIn("competitors_plan", main)
        self.assertIn("competitors_remove", main)
        self.assertIn("collect_inventory", main)
        self.assertIn("collect_cooling", main)
        self.assertIn("profiles_load", main)
        self.assertIn("profiles_save", main)
        self.assertIn("lighting_apply", main)
        self.assertIn("lighting_preview", main)
        self.assertIn("lighting_sync", main)
        self.assertIn("hardware_gauges", main)
        self.assertIn("scan_temps", main)
        self.assertIn("session_load", main)
        self.assertIn("session_save", main)
        self.assertIn("generate_handler!", main)
        self.assertIn("tauri::Builder", main)
        self.assertIn("window_geom", main)
        self.assertIn("single_instance", main)
        self.assertIn("chromaflow-gui.sock", (ROOT / "apps/desktop/src-tauri/src/single_instance.rs").read_text(encoding="utf-8"))
        self.assertNotIn("set_pwm", (ROOT / "apps/desktop/src-tauri/src/single_instance.rs").read_text(encoding="utf-8"))
        self.assertIn("CloseRequested", (ROOT / "apps/desktop/src-tauri/src/window_geom.rs").read_text(encoding="utf-8"))
        self.assertIn("window.json", (ROOT / "apps/desktop/src-tauri/src/window_geom.rs").read_text(encoding="utf-8"))
        self.assertIn("pwm_takeover", main)
        self.assertIn("pwm_tick", main)
        self.assertIn("pwm_release", main)
        self.assertIn("pwm_load", main)
        self.assertIn("pwm_store", main)
        self.assertIn("pwm_calibrate", main)
        self.assertIn("pwm_daemon", main)
        self.assertIn("is_active", main)
        self.assertIn("failsafe", main)
        self.assertNotIn("set_pwm", (ROOT / "apps/desktop/src-tauri/src/window_geom.rs").read_text(encoding="utf-8"))
        self.assertNotIn("set_pwm", main)
        self.assertIn("prepare_webkit", main)
        self.assertIn("start_user_unit", main)
        self.assertIn("ensure_sdk", main)
        self.assertIn("WEBKIT_DISABLE_DMABUF_RENDERER", main)
        build_rs = (ROOT / "apps/desktop/src-tauri/build.rs").read_text(encoding="utf-8")
        self.assertIn("./assets/", build_rs)
        self.assertIn("PROFILE", build_rs)
        vite = (ROOT / "apps/desktop/vite.config.js").read_text(encoding="utf-8")
        self.assertIn('base: "./"', vite)

    def test_support_invokes_when_tauri(self) -> None:
        page = (ROOT / "apps/desktop/src/pages/Support.svelte").read_text(encoding="utf-8")
        helper = (ROOT / "apps/desktop/src/lib/tauri.js").read_text(encoding="utf-8")
        self.assertIn("from \"../lib/tauri.js\"", page)
        self.assertIn("support_dry_run", page)
        self.assertIn("support_apply", page)
        self.assertIn("competitors_plan", page)
        self.assertIn("competitors_remove", page)
        self.assertIn("__TAURI_INTERNALS__", helper)
        self.assertIn("@tauri-apps/api/core", helper)
        self.assertIn("live-support.json", page)
        self.assertIn("live-support-advanced.json", page)
        caps = (ROOT / "apps/desktop/src-tauri/capabilities/default.json").read_text(encoding="utf-8")
        self.assertIn("allow-competitors", caps)

    def test_app_loads_live_inventory(self) -> None:
        app = (ROOT / "apps/desktop/src/App.svelte").read_text(encoding="utf-8")
        self.assertIn('invoke("inventory", { light })', app)
        self.assertIn("live-inventory.json", app)
        self.assertIn("setTimeout", app)
        self.assertNotIn("setInterval", app)
        self.assertIn("pausePoll", (ROOT / "apps/desktop/src/lib/ui.js").read_text(encoding="utf-8"))
        cooling = (ROOT / "apps/desktop/src/pages/Cooling.svelte").read_text(encoding="utf-8")
        app = (ROOT / "apps/desktop/src/App.svelte").read_text(encoding="utf-8")
        self.assertIn("featuredChip", (ROOT / "apps/desktop/src/lib/cooling.js").read_text(encoding="utf-8"))
        self.assertIn("milliC", (ROOT / "apps/desktop/src/lib/cooling.js").read_text(encoding="utf-8"))
        self.assertIn("fc-shell", cooling)
        self.assertIn("FansList", cooling)
        self.assertIn("fc-rail", app)
        self.assertIn("fc-top", app)

    def test_ci_installs_webkit_on_both_ubuntu(self) -> None:
        workflow = (ROOT / ".github/workflows/chromaflow.yml").read_text(encoding="utf-8")
        self.assertIn("libwebkit2gtk-4.1-dev", workflow)
        self.assertIn("ubuntu-22.04", workflow)
        self.assertIn("ubuntu-24.04", workflow)
        self.assertIn("continue-on-error: ${{ matrix.os == 'ubuntu-22.04' }}", workflow)
        self.assertIn("cargo test --workspace --exclude chromaflow-desktop", workflow)
        self.assertIn("cargo build -p chromaflow-desktop --features custom-protocol", workflow)

    def test_default_members_skip_tauri(self) -> None:
        cargo = (ROOT / "Cargo.toml").read_text(encoding="utf-8")
        self.assertIn("default-members", cargo)
        self.assertIn("crates/chromaflow-cli", cargo)
        self.assertIn("apps/desktop/src-tauri", cargo)

    def test_native_window_not_browser(self) -> None:
        conf = (ROOT / "apps/desktop/src-tauri/tauri.conf.json").read_text(encoding="utf-8")
        self.assertIn('"decorations": true', conf)
        self.assertIn('"center": true', conf)
        self.assertIn('"minWidth": 720', conf)
        self.assertIn("http://127.0.0.1:1420/*", (ROOT / "apps/desktop/src-tauri/capabilities/default.json").read_text(encoding="utf-8"))
        self.assertIn("http://asset.localhost/*", (ROOT / "apps/desktop/src-tauri/capabilities/default.json").read_text(encoding="utf-8"))
        self.assertIn("tauri://localhost/*", (ROOT / "apps/desktop/src-tauri/capabilities/default.json").read_text(encoding="utf-8"))
        cargo = (ROOT / "apps/desktop/src-tauri/Cargo.toml").read_text(encoding="utf-8")
        main = (ROOT / "apps/desktop/src-tauri/src/main.rs").read_text(encoding="utf-8")
        self.assertIn("custom-protocol", cargo)
        self.assertIn("--features custom-protocol", (ROOT / "scripts/build-chromaflow-deb.sh").read_text(encoding="utf-8"))
        self.assertIn("cargo build -p chromaflow-desktop --features custom-protocol", (ROOT / ".github/workflows/chromaflow.yml").read_text(encoding="utf-8"))
        self.assertIn("allow-lighting-engine-install", (ROOT / "apps/desktop/src-tauri/capabilities/default.json").read_text(encoding="utf-8"))
        self.assertIn("lighting_preview", (ROOT / "apps/desktop/src-tauri/permissions/chromaflow.toml").read_text(encoding="utf-8"))
        self.assertIn("allow-open-url", (ROOT / "apps/desktop/src-tauri/capabilities/default.json").read_text(encoding="utf-8"))
        self.assertIn("allow-support-apply", (ROOT / "apps/desktop/src-tauri/capabilities/default.json").read_text(encoding="utf-8"))
        self.assertIn("ipc:", conf)
        self.assertNotIn("xdg-open", conf)
        desktop = (ROOT / "packaging/chromaflow.desktop").read_text(encoding="utf-8")
        self.assertIn("Exec=chromaflow-gui", desktop)
        self.assertIn("SingleMainWindow=true", desktop)
        self.assertNotIn("http://", desktop)
        self.assertTrue((ROOT / "packaging/icons/chromaflow.svg").is_file())
        self.assertTrue((ROOT / "packaging/icons/chromaflow.png").is_file())
        self.assertTrue((ROOT / "packaging/icons/chromaflow.ico").is_file())
        self.assertTrue((ROOT / "apps/desktop/src-tauri/icons/icon.png").is_file())
        self.assertTrue((ROOT / "apps/desktop/src-tauri/icons/icon.ico").is_file())
        self.assertTrue((ROOT / "apps/desktop/src-tauri/icons/16x16.png").is_file())
        self.assertTrue((ROOT / "apps/desktop/src-tauri/icons/48x48.png").is_file())
        self.assertIn("icon.ico", conf)
        self.assertIn("image-png", cargo)
        self.assertIn("mod icon", main)
        self.assertIn("icon::apply", main)
        self.assertIn("mod tray", main)
        self.assertIn("tray::attach", main)
        self.assertIn("prevent_close", main)
        self.assertIn("tray-icon", cargo)
        self.assertIn("48x48.png", (ROOT / "apps/desktop/src-tauri/src/icon.rs").read_text(encoding="utf-8"))
        ico = (ROOT / "apps/desktop/src-tauri/icons/icon.ico").read_bytes()
        self.assertGreater(len(ico), 20_000)
        self.assertEqual(int.from_bytes(ico[4:6], "little"), 9)
        mark = (ROOT / "branding/assets/chromaflow-icon.png").read_bytes()
        self.assertGreater(len(mark), 50_000)
        hero = (ROOT / "branding/assets/chromaflow-icon-hero-glass.png").read_bytes()
        self.assertGreater(len(hero), 50_000)
        self.assertLess(len(hero), 500_000)
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        self.assertIn("chromaflow-icon-hero-glass.png", readme)
        self.assertIn("chromaflow-icon.png", readme)
        self.assertNotIn("Golden Path red triangle", (ROOT / "packaging/icons/chromaflow.svg").read_text(encoding="utf-8"))

    def test_lighting_lists_sdk_controllers(self) -> None:
        lighting = (ROOT / "apps/desktop/src/pages/Lighting.svelte").read_text(encoding="utf-8")
        self.assertNotIn("support_dry_run", lighting)
        self.assertNotIn("support_apply", lighting)
        self.assertIn("hid_rgb", (ROOT / "apps/desktop/src/lib/lighting.js").read_text(encoding="utf-8"))
        self.assertIn("lighting.title", (ROOT / "apps/desktop/src/locales/en.json").read_text(encoding="utf-8"))
        self.assertIn("pub fn probe", (ROOT / "crates/chromaflow-core/src/openrgb.rs").read_text(encoding="utf-8"))
        self.assertNotIn("set_pwm", (ROOT / "crates/chromaflow-core/src/openrgb.rs").read_text(encoding="utf-8"))
        self.assertIn("RgbDevice", (ROOT / "crates/chromaflow-core/src/types.rs").read_text(encoding="utf-8"))
        self.assertIn("lighting_apply", lighting)
        self.assertIn("applyAll", lighting)
        self.assertIn("DeviceList", lighting)
        self.assertIn("UPDATE_LEDS", (ROOT / "crates/chromaflow-core/src/openrgb_proto.rs").read_text(encoding="utf-8"))

    def test_profiles_bind_curve_and_rgb(self) -> None:
        page = (ROOT / "apps/desktop/src/pages/Profiles.svelte").read_text(encoding="utf-8")
        self.assertIn("profiles_save", page)
        self.assertIn("curve_set", page)
        locales = (ROOT / "apps/desktop/src/locales/en.json").read_text(encoding="utf-8")
        self.assertIn("profiles.title", locales)
        self.assertIn("support.advanced", locales)
        support = (ROOT / "apps/desktop/src/pages/Support.svelte").read_text(encoding="utf-8")
        extras_card = support.split('t["lighting.extras"]')[1].split("<div class=\"card\">")[0]
        self.assertIn("support.advanced", extras_card)
        self.assertNotIn("thisMachine", support)
        self.assertNotIn("would_modules_load_d", support)
        self.assertNotIn("support.dryRun", support)
        self.assertIn("advanced", support)
        self.assertIn("extras", support)
        self.assertNotIn("deviceForm", support)
        lighting = (ROOT / "apps/desktop/src/pages/Lighting.svelte").read_text(encoding="utf-8")
        self.assertIn("researchDevices", lighting)
        self.assertIn("open_url", (ROOT / "apps/desktop/src/lib/ResearchList.svelte").read_text(encoding="utf-8"))
        self.assertIn("support_apply", support)

    def test_session_persists_tab_and_effects(self) -> None:
        app = (ROOT / "apps/desktop/src/App.svelte").read_text(encoding="utf-8")
        session_js = (ROOT / "apps/desktop/src/lib/session.js").read_text(encoding="utf-8")
        session_rs = (ROOT / "apps/desktop/src-tauri/src/session.rs").read_text(encoding="utf-8")
        main = (ROOT / "apps/desktop/src-tauri/src/main.rs").read_text(encoding="utf-8")
        caps = (ROOT / "apps/desktop/src-tauri/capabilities/default.json").read_text(encoding="utf-8")
        perm = (ROOT / "apps/desktop/src-tauri/permissions/chromaflow.toml").read_text(encoding="utf-8")
        self.assertIn("loadLocal", app)
        self.assertIn("setTab", app)
        self.assertIn('{#if tab === "Cooling"}', app)
        self.assertIn("session_load", session_js)
        self.assertIn("chromaflow.session", session_js)
        self.assertIn("session.json", session_rs)
        self.assertIn("fn sanitize", session_rs)
        self.assertIn("session_load", main)
        self.assertIn("session_save", main)
        self.assertIn("allow-session", caps)
        self.assertIn("allow-session", perm)
        self.assertIn("allow-pwm", caps)
        self.assertIn("allow-pwm", perm)
        self.assertNotIn("set_pwm", session_rs)
        self.assertNotIn("set_pwm", session_js)


if __name__ == "__main__":
    unittest.main()
