"""Extract OpenRGB detector identity (name, bus, IDs). Never copies controller bodies."""
from __future__ import annotations

import csv
import re
from pathlib import Path

HID = re.compile(
    r"^\s*REGISTER_HID_DETECTOR(?:_[A-Z]+)*\("
    r'\s*"(?P<name>[^"]+)"\s*,\s*(?P<func>[A-Za-z0-9_]+)\s*,'
    r"\s*(?P<vid>[A-Za-z0-9_]+)\s*,\s*(?P<pid>[A-Za-z0-9_]+)",
    re.M,
)
I2C = re.compile(
    r"^\s*REGISTER_I2C_PCI_DETECTOR\("
    r'\s*"(?P<name>[^"]+)"\s*,\s*(?P<func>[A-Za-z0-9_]+)\s*,'
    r"\s*(?P<vid>[A-Za-z0-9_]+)\s*,\s*(?P<pid>[A-Za-z0-9_]+)\s*,"
    r"\s*(?P<svid>[A-Za-z0-9_]+)\s*,\s*(?P<spid>[A-Za-z0-9_]+)",
    re.M,
)
DEFINE = re.compile(r"^\s*#define\s+([A-Za-z0-9_]+)\s+(0x[0-9A-Fa-f]+|-1|\d+)\s*$", re.M)
HEX = re.compile(r"^0x[0-9A-Fa-f]+$")


def _hex(token: str, defs: dict[str, str]) -> str:
    cur = token
    for _ in range(8):
        if cur in ("HID_PID_ANY", "HID_VID_ANY") or defs.get(cur) in ("-1",):
            return "any"
        if HEX.match(cur):
            return cur[2:].lower().zfill(4)
        if cur.isdigit():
            return format(int(cur), "x").zfill(4)
        nxt = defs.get(cur)
        if not nxt:
            return ""
        cur = nxt
    return ""


def _defs(root: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for path in [root / "pci_ids/pci_ids.h", root / "DetectionManager.h"]:
        if path.is_file():
            out.update(DEFINE.findall(path.read_text(encoding="utf-8", errors="replace")))
    for path in root.joinpath("Controllers").rglob("*"):
        if path.suffix.lower() in {".h", ".hpp", ".cpp", ".c"}:
            out.update(DEFINE.findall(path.read_text(encoding="utf-8", errors="replace")))
    return out


def extract_rows(root: Path) -> list[dict[str, str]]:
    defs = _defs(root)
    rows: list[dict[str, str]] = []
    seen: set[tuple[str, ...]] = set()
    for path in sorted(root.joinpath("Controllers").rglob("*Detect*")):
        if path.suffix.lower() not in {".cpp", ".c", ".h"}:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for kind, rx, bus in (("USB", HID, "USB"), ("I2C", I2C, "I2C")):
            for m in rx.finditer(text):
                head = text[m.start() : m.start() + 48]
                if "DISABLED" in head:
                    continue
                vid = _hex(m.group("vid"), defs)
                pid = _hex(m.group("pid"), defs)
                svid = _hex(m.groupdict().get("svid") or "", defs) if "svid" in m.groupdict() else ""
                spid = _hex(m.groupdict().get("spid") or "", defs) if "spid" in m.groupdict() else ""
                if kind == "USB" and not vid:
                    continue
                if kind == "I2C" and not (vid and pid):
                    continue
                key = (m.group("name"), bus, vid, pid, svid, spid)
                if key in seen:
                    continue
                seen.add(key)
                cat = "Keyboard" if "key" in m.group("name").lower() else ("GPU" if bus == "I2C" else "USB")
                rows.append(
                    {
                        "Name": m.group("name"),
                        "Category": cat,
                        "Type": bus,
                        "RGBController": m.group("func").removeprefix("Detect"),
                        "VID": vid,
                        "PID": pid,
                        "SVID": svid,
                        "SPID": spid,
                    }
                )
    rows.sort(key=lambda r: (r["Type"], r["VID"], r["PID"], r["Name"]))
    return rows


def write_csv(rows: list[dict[str, str]], dest: Path, revision: str) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    header = [
        f"# OpenRGB detector identity index (name/bus/IDs only). Source revision {revision}.",
        "# OpenRGB is GPL-2.0-or-later (Adam Honse / contributors). Not a protocol dump.",
        "# Regenerated by python3 scripts/agent-run.py fetch-openrgb-device-index",
    ]
    fields = ["Name", "Category", "Type", "RGBController", "VID", "PID", "SVID", "SPID"]
    with dest.open("w", encoding="utf-8", newline="") as fh:
        fh.write("\n".join(header) + "\n")
        w = csv.DictWriter(fh, fieldnames=fields, lineterminator="\n")
        w.writeheader()
        w.writerows(rows)


def main() -> int:
    import os
    import sys

    src = Path(os.environ.get("CHROMAFLOW_OPENRGB_SRC") or sys.argv[1])
    dest = Path(os.environ.get("CHROMAFLOW_DEVICE_INDEX") or "data/openrgb-device-index.csv")
    rev = os.environ.get("CHROMAFLOW_OPENRGB_REV") or "unknown"
    rows = extract_rows(src)
    if len(rows) < 50:
        print(f"too few detector rows: {len(rows)}", file=sys.stderr)
        return 2
    write_csv(rows, dest, rev)
    print(f"{dest} {len(rows)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
